blank_issues_enabled: false
contact_links:
  - name: Official MyAnimeList API Club
    url: https://myanimelist.net/clubs.php?cid=13727
    about: We do not maintain the MyAnimeList API, issues regarding the API itself should be posted in their official club