name: Deploy Site
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Bundle Install
        run: |
          bundle install

      - name: Build Site
        run: |
          npm i

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          force_orphan: true
          user_name: mashiro-san
          user_email: mashiro-san@users.noreply.github.com
          commit_message: ${{ github.event.head_commit.message }}